### ISSUE TITLE
CS0246 C# The type or namespace name could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by MePride** [LavamasterYT/AirPodsUI#1]
can't find class or namespace [RegistryUtils]

**Comment by LavamasterYT** [comment]
You need to install the Microsoft.Win32.Registry Nuget Package.

**Comment by yarnacles** [comment]
I have installed the Win32.Registry package through package manager yet I still get the same problems asking for RegistryUtils and RegistryMonitor
